### ISSUE TITLE
framework not resilient to node restart - version 0.3.0

### ISSUE THREAD

**Issue by mikestaub** [arangodb/arangodb-dcos#5]
After restarting the node that is running the "arangodb" mesos task, the new arangodb task throws the following error (check below for full error log): 

`ArangoScheduler.cpp:483] ERROR Framework has been removed`

To get the cluster running again I have to completely uninstall and reinstall the dcos package, which is a similar issue to the one described here:
https://github.com/arangodb/arangodb-mesos-framework/issues/3

When I restart nodes running any of the other arangodb tasks, over time the cluster recovers. Are there plans to address this single point of failure for the cluster? I was hoping since this version uses mesos persistent volumes, recovery from node restarts would be possible.

I0222 19:26:59.645720 22283 exec.cpp:136] Version: 0.26.0
I0222 19:26:59.649775 22288 exec.cpp:210] Executor registered on slave 022b48f3-e3f9-4bf4-a8c5-0e28779df418-S12
I0222 19:26:59.770282     1 framework.cpp:395] ArangoDB Image: arangodb/arangodb-mesos:mesosphere-V2
I0222 19:26:59.770362     1 framework.cpp:407] Mode: cluster
I0222 19:26:59.770375     1 framework.cpp:410] Asynchronous replication flag: 1
I0222 19:26:59.770383     1 framework.cpp:416] SecondariesWithDBservers: 0
I0222 19:26:59.770390     1 framework.cpp:419] CoordinatorsWithDBservers: 0
I0222 19:26:59.770396     1 framework.cpp:422] SecondarySameServer: 0
I0222 19:26:59.770403     1 framework.cpp:425] ArangoDBPrivilegedImage: 0
I0222 19:26:59.770411     1 framework.cpp:427] Minimal resources agent: mem(_):512;cpus(_):0.25;disk(_):512
I0222 19:26:59.770417     1 framework.cpp:429] Minimal resources DBserver: mem(_):1024;cpus(_):1;disk(_):1024
I0222 19:26:59.770423     1 framework.cpp:431] Minimal resources secondary DBserver: mem(_):1024;cpus(_):1;disk(_):1024
I0222 19:26:59.770431     1 framework.cpp:434] Minimal resources coordinator: mem(_):1024;cpus(_):1;disk(_):1024
I0222 19:26:59.770437     1 framework.cpp:437] Number of agents in agency: 1
I0222 19:26:59.770444     1 framework.cpp:439] Number of DBservers: 2
I0222 19:26:59.770452     1 framework.cpp:441] Number of coordinators: 1
I0222 19:26:59.770457     1 framework.cpp:448] zookeeper: zk://master.mesos:2181/arangodb/arangodb
2016-02-22 19:26:59,772:1(0x7fd71ec1e700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2016-02-22 19:26:59,772:1(0x7fd71ec1e700):ZOO_INFO@log_env@716: Client environment:host.name=ip-10-40-74-49.ec2.internal
2016-02-22 19:26:59,772:1(0x7fd71ec1e700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2016-02-22 19:26:59,772:1(0x7fd71ec1e700):ZOO_INFO@log_env@724: Client environment:os.arch=4.1.7-coreos-r1
2016-02-22 19:26:59,772:1(0x7fd71ec1e700):ZOO_INFO@log_env@725: Client environment:os.version=#2 SMP Thu Nov 5 02:10:23 UTC 2015
2016-02-22 19:26:59,772:1(0x7fd71ec1e700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2016-02-22 19:26:59,772:1(0x7fd71ec1e700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2016-02-22 19:26:59,772:1(0x7fd71ec1e700):ZOO_INFO@log_env@753: Client environment:user.dir=/mesos
2016-02-22 19:26:59,772:1(0x7fd71ec1e700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=master.mesos:2181 sessionTimeout=120000 watcher=0xd396f8 sessionId=0 sessionPasswd=<null> context=0x7fd710000d08 flags=0
2016-02-22 19:26:59,775:1(0x7fd6ff9d2700):ZOO_INFO@check_events@1703: initiated connection to server [10.40.74.181:2181]
2016-02-22 19:26:59,779:1(0x7fd6ff9d2700):ZOO_INFO@check_events@1750: session establishment complete on server [10.40.74.181:2181], sessionId=0x152f72f458d0684, negotiated timeout=40000
I0222 19:26:59.784219     1 ArangoState.cpp:175] current state: <removed-for-brevity>
I0222 19:26:59.784250     1 framework.cpp:469] framework user: 
I0222 19:26:59.784261     1 framework.cpp:473] framework name: arangodb
I0222 19:26:59.784268     1 framework.cpp:476] role: arangodb
I0222 19:26:59.784318     1 framework.cpp:485] failover timeout: 30
I0222 19:26:59.784431     1 framework.cpp:505] webui url: http://10.40.74.49:19352
I0222 19:26:59.794597    18 ArangoState.h:143] Did not get lease of state, waiting 1 sec...
I0222 19:26:59.794654     1 ArangoManager.cpp:1075] recovering instance type 1
I0222 19:26:59.794770     1 ArangoManager.cpp:1084] for task id 3abd35c5-eed8-4890-98a2-50b206d097a5: 0
I0222 19:26:59.794785     1 ArangoManager.cpp:1075] recovering instance type 2
I0222 19:26:59.794795     1 ArangoManager.cpp:1084] for task id cfdfbe33-1d94-40e0-8401-e55c9527688a: 0
I0222 19:26:59.794803     1 ArangoManager.cpp:1075] recovering instance type 3
I0222 19:26:59.794811     1 ArangoManager.cpp:1084] for task id f31a65d9-2030-41a7-ab45-fa8e75f46211: 0
I0222 19:26:59.794819     1 ArangoManager.cpp:1084] for task id ff8ff154-0fd7-41a5-bef5-a57c3b39352f: 1
I0222 19:26:59.794828     1 ArangoManager.cpp:1075] recovering instance type 4
I0222 19:26:59.794836     1 ArangoManager.cpp:1084] for task id b8973a50-d724-4014-ad79-c71502bc1811: 0
I0222 19:26:59.794844     1 ArangoManager.cpp:1084] for task id c4904e4a-adc1-43f4-bb86-e434a0c28208: 3
I0222 19:27:01.798620     1 framework.cpp:595] http port: 19352
2016-02-22 19:27:01,798:1(0x7fd71d41b700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2016-02-22 19:27:01,799:1(0x7fd71d41b700):ZOO_INFO@log_env@716: Client environment:host.name=ip-10-40-74-49.ec2.internal
2016-02-22 19:27:01,799:1(0x7fd71d41b700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2016-02-22 19:27:01,799:1(0x7fd71d41b700):ZOO_INFO@log_env@724: Client environment:os.arch=4.1.7-coreos-r1
2016-02-22 19:27:01,799:1(0x7fd71d41b700):ZOO_INFO@log_env@725: Client environment:os.version=#2 SMP Thu Nov 5 02:10:23 UTC 2015
2016-02-22 19:27:01,799:1(0x7fd71d41b700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2016-02-22 19:27:01,799:1(0x7fd71d41b700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2016-02-22 19:27:01,799:1(0x7fd71d41b700):ZOO_INFO@log_env@753: Client environment:user.dir=/mesos
2016-02-22 19:27:01,799:1(0x7fd71d41b700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=master.mesos:2181 sessionTimeout=10000 watcher=0xd396f8 sessionId=0 sessionPasswd=<null> context=0x7fd6f4000e18 flags=0
I0222 19:27:01.799757     1 sched.cpp:166] Version: 0.26.0
2016-02-22 19:27:01,804:1(0x7fd6fd9ce700):ZOO_INFO@check_events@1703: initiated connection to server [10.40.74.181:2181]
2016-02-22 19:27:01,811:1(0x7fd6fd9ce700):ZOO_INFO@check_events@1750: session establishment complete on server [10.40.74.181:2181], sessionId=0x152f72f458d0685, negotiated timeout=10000
I0222 19:27:01.811960    11 group.cpp:331] Group process (group(1)@10.40.74.49:19353) connected to ZooKeeper
I0222 19:27:01.812115    11 group.cpp:805] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0222 19:27:01.812216    11 group.cpp:403] Trying to create path '/mesos' in ZooKeeper
I0222 19:27:01.817447    11 detector.cpp:156] Detected a new leader: (id='8')
I0222 19:27:01.817632    11 group.cpp:674] Trying to get '/mesos/json.info_0000000008' in ZooKeeper
I0222 19:27:01.822896     8 detector.cpp:482] A new leading master (UPID=master@10.40.74.182:5050) is detected
I0222 19:27:01.822999     8 sched.cpp:264] New master detected at master@10.40.74.182:5050
I0222 19:27:01.823292     8 sched.cpp:274] No credentials provided. Attempting to register without authentication
I0222 19:27:01.825906    11 sched.cpp:1027] Got error 'Framework has been removed'
I0222 19:27:01.825994    11 sched.cpp:1839] Asked to abort the driver
E0222 19:27:01.826061    11 ArangoScheduler.cpp:483] ERROR Framework has been removed
I0222 19:27:01.826169    11 sched.cpp:1073] Aborting framework '98ac5ce5-ea48-44de-afe0-4ee7d0e41c6b-0008'
I0222 19:27:01.826283     1 sched.cpp:1805] Asked to stop the driver
2016-02-22 19:27:01,826:1(0x7fd72b9b77c0):ZOO_INFO@zookeeper_close@2505: Closing zookeeper sessionId=0x152f72f458d0685 to [10.40.74.181:2181]

I0222 19:27:06.367805    19 HttpServer.cpp:437] handling http request 'GET /v1/health.json'
2016-02-22 19:27:14,145:1(0x7fd6ff9d2700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 13ms
I0222 19:27:16.376979    19 HttpServer.cpp:437] handling http request 'GET /v1/health.json'
I0222 19:27:26.386775    19 HttpServer.cpp:437] handling http request 'GET /v1/health.json'
2016-02-22 19:27:27,492:1(0x7fd6ff9d2700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 13ms
I0222 19:27:36.406637    19 HttpServer.cpp:437] handling http request 'GET /v1/health.json'

**Comment by m0ppers** [comment]
wow...We are able to reproduce this issue. We are investigating and trying to automate some more tests. Killing the framework task seems to work properly but when stopping the slave the framework is running on we seem to hit some timeouts and we are unregistered.

**Comment by joerg84** [comment]
@m0ppers: As discussed could you check the failover_timeout (https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L222) and potentially raise it?

**Comment by m0ppers** [comment]
ok it seems we completely misunderstood this specific timeout :S I have increased its default value. Pull request is ongoing:

https://github.com/mesosphere/universe/pull/310

Meanwhile you can als configure it in your local arangodb dcos config.

Sorry. That should not happen :| We need more automated tests on our side. Working on it.

**Comment by mikestaub** [comment]
Thanks for resolving this so fast!

**Comment by mikestaub** [comment]
So although increasing the timeout resolved the framework from being uninstalled, when I restart the node running the "arangodb" task the cluster still doesn't seem to recover correctly. One of the dbserver tasks became lost and was never relaunched. When I ran `dcos arangodb dbservers` it listed it as running, which I'm guessing was the problem.

I only tested this once, so I will definitely try again and see if I can create a reproducible scenario for you.

The only reason I'm harping on this is because we have been using arangodb for months now in dev (we love it btw), but will soon be using it in our production cluster. I want to be sure it is as resilient as possible to node failures, which are rare but inevitable.

**Comment by neunhoef** [comment]
We would like to investigate this further. It would be most helpful if you could send us more details as to what you did. I read your report as "I rebooted the node on which the framework scheduler runs", and there was one DBserver on the same machine as well. Is that right?

You write the DBserver "never" came back? For how long did you wait? We have some timeouts for recovery, which might be too large. I think we wait for 15 minutes in the hope that a server with a persistent volume comes back before we declare it dead and schedule a new one. If a DBserver fails, then its secondary (if you have asynchronous replication switched on) should kick in after 5 minutes.

Would it be possible to get the stdout and stderr output from the sandbox of the arangodb task, ideally the one before the reboot and the one from after the reboot which got automatically restarted by Marathon. Note that this new one could be on another node!

Furthermore, it would be useful to know more about your setup, you seem to be using the Mesosphere DCOS setup. I presume you are running on AWS, using Mesosphere's Cloud Formation template? Which version of DCOS/Mesos are you using?

We do already know that, depending on how long the node is away, the mesos master might already have declared the mesos slave together with all its task to be dead (as far as we know, the timeout is about one minute). In that case it refuses to work with the rebooted slave, which in turn terminates. The system then starts a new Mesos slave on that machine, with a new ID. There could be a problem if the new slave picks up the persisted and reserved resources and tries to offer them back to us...

Anyway, it would be great if we could reproduce the problem and fix it.

Apart from that we would in general be interested to learn more about what you do with ArangoDB, maybe we could support you, if only to answer questions or fix problems. If you have any question you can also contact me privately by email via max at arangodb.com

**Comment by mikestaub** [comment]
Hi Max, thanks for your reply. I am currently running on AWS using DCOS 1.5.2 (mesos 0.26.0)

I wasn't able to reproduce the above scenario so it must have been something on my end, perhaps I did not wait the full 15 minutes.

I do have one more question: what exactly is the "arangodb" mesos task responsible for? If it goes down for a minute, can clients still communicate with the coordinators?

Moving forward if I have any urgent issues I will contact you via email.

`
